
# Installation du cluster consul
- hosts: consul-cluster
  become: yes
  become_user: root
  vars:
    consul_is_server: true
    consul_is_ui: true
    consul_client_address: "0.0.0.0"
    consul_retry_join: true
    consul_bootstrap_expect: 3
    consul_encrypt: iuEOzrCGw0dmiis1fMChmg==
  roles:
    - consul
    - consul-cluster


# Installation des clients consul
- hosts: consul-clients
  become: yes
  become_user: root
  vars:
    consul_is_server: false
    consul_join_at_start: true
    consul_client_address: "127.0.0.1"
    consul_encrypt: iuEOzrCGw0dmiis1fMChmg==
  roles:
    - consul
  tags:
    - consul
    - consul-clients
