---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart consul
  action: service name=consul state=restarted enabled=yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: reload consul config
  become: yes
  command: pkill -1 consul
  when: consul_service_state is not "stopped" and consul_manage_service
